In [3]:
import pandas as pd

In [4]:
# Read the customer dataset
data = pd.read_csv("olist_customer.csv")
df = data.copy()

In [5]:
df.head()

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,0,0,0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,1,1,1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,2,2,2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,3,3,3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4,4,4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [6]:
df.tail()

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
99436,99436,99436,99436,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,3937,sao paulo,SP
99437,99437,99437,99437,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,6764,taboao da serra,SP
99438,99438,99438,99438,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,60115,fortaleza,CE
99439,99439,99439,99439,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,92120,canoas,RS
99440,99440,99440,99440,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,6703,cotia,SP

In [7]:
# Check dataset information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Unnamed: 0.2              99441 non-null  int64
 1   Unnamed: 0.1              99441 non-null  int64
 2   Unnamed: 0                99441 non-null  int64
 3   customer_id               99441 non-null  object
 4   customer_unique_id        99441 non-null  object
 5   customer_zip_code_prefix  99441 non-null  int64
 6   customer_city             99441 non-null  object
 7   customer_state            99441 non-null  object
dtypes: int64(4), object(4)
memory usage: 6.1+ MB

In [8]:
# Check missing values
df.isnull().sum()

Unnamed: 0.2                0
Unnamed: 0.1                0
Unnamed: 0                  0
customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [9]:
# Check duplicate records
df.duplicated().sum()

np.int64(0)

In [10]:
df.columns

Index(['Unnamed: 0.2', 'Unnamed: 0.1', 'Unnamed: 0', 'customer_id',
       'customer_unique_id', 'customer_zip_code_prefix', 'customer_city',
       'customer_state'],
      dtype='object')

In [11]:
# Check data types
df.dtypes

Unnamed: 0.2                 int64
Unnamed: 0.1                 int64
Unnamed: 0                   int64
customer_id                 object
customer_unique_id          object
customer_zip_code_prefix     int64
customer_city               object
customer_state              object
dtype: object

In [12]:
df.to_csv("olist_customer.csv")

In [13]:
# Read the order items dataset
data1 = pd.read_csv("olist_geolocations.csv")

In [14]:
df1 = data1.copy()

In [15]:
df1.head()

,Unnamed: 0.1,Unnamed: 0,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,0,0,1037,-23.545621,-46.639292,sao paulo,SP
1,1,1,1046,-23.546081,-46.644820,sao paulo,SP
2,2,2,1046,-23.546129,-46.642951,sao paulo,SP
3,3,3,1041,-23.544392,-46.639499,sao paulo,SP
4,4,4,1035,-23.541578,-46.641607,sao paulo,SP

In [16]:
df1.tail()

,Unnamed: 0.1,Unnamed: 0,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
738327,738327,1000155,99965,-28.180655,-52.034367,agua santa,RS
738328,738328,1000156,99950,-28.072188,-52.011272,tapejara,RS
738329,738329,1000157,99950,-28.068864,-52.012964,tapejara,RS
738330,738330,1000158,99950,-28.068639,-52.010705,tapejara,RS
738331,738331,1000161,99980,-28.388932,-51.846871,david canabarro,RS

In [17]:
# Check dataset information
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 738332 entries, 0 to 738331
Data columns (total 7 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Unnamed: 0.1                 738332 non-null  int64
 1   Unnamed: 0                   738332 non-null  int64
 2   geolocation_zip_code_prefix  738332 non-null  int64
 3   geolocation_lat              738332 non-null  float64
 4   geolocation_lng              738332 non-null  float64
 5   geolocation_city             738332 non-null  object
 6   geolocation_state            738332 non-null  object
dtypes: float64(2), int64(3), object(2)
memory usage: 39.4+ MB

In [18]:
# Check duplicate records
df1[df1.duplicated()]

Empty DataFrame
Columns: [Unnamed: 0.1, Unnamed: 0, geolocation_zip_code_prefix, geolocation_lat, geolocation_lng, geolocation_city, geolocation_state]
Index: []

In [19]:
df1[df1.duplicated(keep=False)]

Empty DataFrame
Columns: [Unnamed: 0.1, Unnamed: 0, geolocation_zip_code_prefix, geolocation_lat, geolocation_lng, geolocation_city, geolocation_state]
Index: []

In [20]:
df1 = df1.drop_duplicates()

In [21]:
df1.nunique()

Unnamed: 0.1                   738332
Unnamed: 0                     738332
geolocation_zip_code_prefix     19015
geolocation_lat                717349
geolocation_lng                717613
geolocation_city                 8011
geolocation_state                  27
dtype: int64

In [22]:
# Check duplicate records
df1.duplicated().sum()

np.int64(0)

In [23]:
# Check missing values
df1.isnull().sum()

Unnamed: 0.1                   0
Unnamed: 0                     0
geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

In [24]:
# Check dataset information
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 738332 entries, 0 to 738331
Data columns (total 7 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Unnamed: 0.1                 738332 non-null  int64
 1   Unnamed: 0                   738332 non-null  int64
 2   geolocation_zip_code_prefix  738332 non-null  int64
 3   geolocation_lat              738332 non-null  float64
 4   geolocation_lng              738332 non-null  float64
 5   geolocation_city             738332 non-null  object
 6   geolocation_state            738332 non-null  object
dtypes: float64(2), int64(3), object(2)
memory usage: 39.4+ MB

In [25]:
df1.to_csv("olist_geolocations.csv")

In [26]:
# Read the olist order itme
data2 = pd.read_csv("olist_order_item.csv")
df2 = data2.copy()

In [27]:
df2.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,Year,Month,Date
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,2017,9,2017-09-19
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,2017,5,2017-05-03
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,2018,1,2018-01-18
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,2018,8,2018-08-15
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,2017,2,2017-02-13

In [28]:
# Check dataset information
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 10 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
 7   Year                 112650 non-null  int64
 8   Month                112650 non-null  int64
 9   Date                 112650 non-null  object
dtypes: float64(2), int64(3), object(5)
memory usage: 8.6+ MB

In [29]:
# Check missing values
df2.isnull().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
Year                   0
Month                  0
Date                   0
dtype: int64

In [30]:
# Check duplicate records
df2.duplicated().sum()

np.int64(0)

In [31]:
# there is no null columns or duplicated values 
# now we check the data type and change it's

In [32]:
# Check data types
df2.dtypes

order_id                object
order_item_id            int64
product_id              object
seller_id               object
shipping_limit_date     object
price                  float64
freight_value          float64
Year                     int64
Month                    int64
Date                    object
dtype: object

In [33]:
# convert the data types
df2["shipping_limit_date"] = pd.to_datetime(df2["shipping_limit_date"] 
                                             )

In [34]:
df2["Year"]= df2["shipping_limit_date"].dt.year

In [35]:
df2["Month"] = df2["shipping_limit_date"].dt.month

In [36]:
df2["Date"] = df2["shipping_limit_date"].dt.date

In [37]:
df2.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,Year,Month,Date
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,2017,9,2017-09-19
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,2017,5,2017-05-03
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,2018,1,2018-01-18
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,2018,8,2018-08-15
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,2017,2,2017-02-13

In [38]:
# Check dataset information
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 10 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  datetime64[ns]
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
 7   Year                 112650 non-null  int32
 8   Month                112650 non-null  int32
 9   Date                 112650 non-null  object
dtypes: datetime64[ns](1), float64(2), int32(2), int64(1), object(4)
memory usage: 7.7+ MB

In [39]:
data2 = df2.copy()

In [40]:
data2.to_csv("olist_order_item.csv",index=False)

In [41]:
# Read the order order payments
data3 = pd.read_csv("olist_order_payments.csv")
df3 = data3.copy()

In [42]:
df3.head()
df3.tail()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
103881,0406037ad97740d563a178ecc7a2075c,1,boleto,1,363.31
103882,7b905861d7c825891d6347454ea7863f,1,credit_card,2,96.80
103883,32609bbb3dd69b3c066a6860554a77bf,1,credit_card,1,47.77
103884,b8b61059626efa996a60be9bb9320e10,1,credit_card,5,369.54
103885,28bbae6599b09d39ca406b747b6632b1,1,boleto,1,191.58

In [43]:
# Check dataset information
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB

In [44]:
df3.describe()

       payment_sequential  payment_installments  payment_value
count       103886.000000         103886.000000  103886.000000
mean             1.092679              2.853349     154.100380
std              0.706584              2.687051     217.494064
min              1.000000              0.000000       0.000000
25%              1.000000              1.000000      56.790000
50%              1.000000              1.000000     100.000000
75%              1.000000              4.000000     171.837500
max             29.000000             24.000000   13664.080000

In [45]:
# Check missing values
df3.isnull().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [46]:
# Check duplicate records
df3.duplicated().sum()

np.int64(0)

In [47]:
# all file are okay
df3.isna().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [48]:
# Read the order order reviews
data_04 = pd.read_csv("olist_order_reviews.csv")
df4 = data_04.copy()

In [49]:
df4.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [50]:
# Check missing values
df4.isnull().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [51]:
# Check duplicate records
df4.duplicated().sum()

np.int64(0)

In [52]:
# there is to much missin g vlaues so we can't remove it 
df4["review_comment_title"] = df4["review_comment_title"].fillna("Unknown")

In [53]:
df4["review_comment_message"] = df4["review_comment_message"].fillna("Unknown")

In [54]:
# Check missing values
df4.isnull().sum()

review_id                  0
order_id                   0
review_score               0
review_comment_title       0
review_comment_message     0
review_creation_date       0
review_answer_timestamp    0
dtype: int64

In [55]:
df4["review_creation_date"] = pd.to_datetime(df4["review_creation_date"])

In [56]:
df4["review_creation_date"].isnull().sum()

np.int64(0)

In [ ]:
df4["review_creation_date"] = pd.to_datetime(df4["review_creation_date"])

In [71]:
df4["Review_creation_date"] = df4["review_creation_date"].dt.date

In [58]:
df4.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,Unknown,Unknown,2018-01-18,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,Unknown,Unknown,2018-03-10,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,Unknown,Unknown,2018-02-17,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,Unknown,Recebi bem antes do prazo estipulado.,2017-04-21,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,Unknown,Parabéns lojas lannister adorei comprar pela I...,2018-03-01,2018-03-02 10:26:53

In [59]:
df4["review_answer_timestamp"]= pd.to_datetime(df4["review_answer_timestamp"])

In [60]:
# Check data types
df4.dtypes

review_id                          object
order_id                           object
review_score                        int64
review_comment_title               object
review_comment_message             object
review_creation_date       datetime64[ns]
review_answer_timestamp    datetime64[ns]
dtype: object

In [ ]:
df4.drop("review_answer_timestam" ,axis=1,inplace=True)

In [62]:
df4["review_answer_date"] = df4["review_answer_timestamp"].dt.date

In [63]:
df4.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,review_answer_date
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,Unknown,Unknown,2018-01-18,2018-01-18 21:46:59,2018-01-18
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,Unknown,Unknown,2018-03-10,2018-03-11 03:05:13,2018-03-11
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,Unknown,Unknown,2018-02-17,2018-02-18 14:36:24,2018-02-18
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,Unknown,Recebi bem antes do prazo estipulado.,2017-04-21,2017-04-21 22:02:06,2017-04-21
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,Unknown,Parabéns lojas lannister adorei comprar pela I...,2018-03-01,2018-03-02 10:26:53,2018-03-02

In [64]:
df4["review_answer_time"] = df4["review_answer_timestamp"].dt.time

In [65]:
df4.drop("review_answer_timestamp", axis=1,inplace=True)

In [66]:
df4.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_date,review_answer_time
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,Unknown,Unknown,2018-01-18,2018-01-18,21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,Unknown,Unknown,2018-03-10,2018-03-11,03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,Unknown,Unknown,2018-02-17,2018-02-18,14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,Unknown,Recebi bem antes do prazo estipulado.,2017-04-21,2017-04-21,22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,Unknown,Parabéns lojas lannister adorei comprar pela I...,2018-03-01,2018-03-02,10:26:53

In [73]:
df4.to_csv("olist_order_review.csv")